name: Docker Image CI

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: rnters/heroku-rails

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repo
        uses: actions/checkout@v2
      # Login against a Docker registry
      # https://github.com/docker/login-action
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: rnters-bot
          password: ${{ secrets.GH_ACTIONS_PAT }}
      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: 2.7.4/.
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:2.7.4,ghcr.io/${{ env.IMAGE_NAME }}:latest
