name: Docker Image CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tags:
          - 18-2.6.6
          - 20-2.6.6
          - 20-2.6.8
          - 20-2.6.9
          - 20-2.6.10
          - 20-2.7.4
          - 20-2.7.5
          - 20-2.7.6
          - 20-2.7.7
          - 20-2.7.8
          - 20-3.0.2
          - 20-3.0.3
          - 20-3.1.2
          - 22-3.1.2
          - 22-3.1.4
          - 22-3.2.2
          - 22-3.2.4
          - 24-3.2.2
          - 24-3.2.4
          - 24-3.3.4
    steps:
      # Checkout this repo
      # https://github.com/actions/checkout
      - name: Checkout repo
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login against a Docker registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: alexcastrodev
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ${{ matrix.tags }}/Dockerfile
          no-cache: true
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/alexcastrodev/heroku-rails:${{ matrix.tags }}
