name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tags:
          - 18-2.6.6
          - 20-2.6.6
          - 20-2.6.8
          - 20-2.6.9
          - 20-2.6.10
          - 20-2.7.4
          - 20-2.7.5
          - 20-2.7.6
          - 20-2.7.7
          - 20-2.7.8
          - 20-3.0.2
          - 20-3.0.3
          - 20-3.1.2
          - 22-3.1.2
          - 22-3.1.4
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v2
      # Login against a Docker registry
      # https://github.com/docker/login-action
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: rnters-bot
          password: ${{ secrets.GH_ACTIONS_PAT }}
      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      -
        name: Build and push ${{ matrix.ruby }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.tags }}/.
          no-cache: true
          push: true
          tags: ghcr.io/rnters/heroku-rails:${{ matrix.tags }}